### ISSUE TITLE
[FR] support `snap` plugin

### ISSUE THREAD

**Issue by bangedorrunt** [pyrho/nerveux.nvim#1]
Hi, could you consider supporting `camspiers/snap` plugin for neuron. This one is an alternative of Telescope but snapier

**Comment by pyrho** [comment]
Hi,

I don't know about `campsiers/snap`, I'll take a look and see if it's worth replacing telescope and if not how we can make this part modular so that each one can use his picker of choice (fzf, clap, etc.).

**Comment by bangedorrunt** [comment]
Thank you, I'm looking forward to it

**Comment by pyrho** [comment]
#### Regarding replacing telescope with snap
snap looks very promising, but I think we need to wait for PR #47 of snap to be merged before we can consider it for this plugin; the strings being filtered are not the ones being opened (zettel title vs file path).

#### Regarding modularity
nerveux.nvim will provide basic search functionality tru the selected picker (telescope for now, something else someday?).
I've added the possibility to disable a single mapping (cf. README) and the function that makes the call to `neuron query` is now exported; so in theory you could unbind `gzz`, create a function that calls `require"nerveux".create_async_query_neuron_function` and feed the results to the picker of your choice.

i will close this issue for now and take another look at this when PR #47 of snap is merged.

**Comment by bangedorrunt** [comment]
@pyrho in the meantime, could you support  [nvim-fzf](https://github.com/vijaymarupudi/nvim-fzf). The reason I don't like Telescope is it's bloated with lots of features that I never use and it's result is limited on display. Sorry if it's too much to ask for

**Comment by pyrho** [comment]
I actually started out using nvim-fzf. There is a branch using it here: https://github.com/pyrho/nerveux.nvim/blob/fzf/lua/nerveux/init.lua#L104 but the code most likely very outdated compared to master; but if I recall correctly basic functionality should work; and perhaps you could use this as a base to maintain your own fork with fzf support.

I don't feel like supporting two pickers is a good idea as it will increase the number of potential bugs and the amount of work required when adding or changing features.

**Comment by bangedorrunt** [comment]
Thank you, that's a good start, guess I will learn me some Lua and how to make a plugin
