### ISSUE TITLE
Search zettels does not work

### ISSUE THREAD

**Issue by ardasevinc** [pyrho/nerveux.nvim#2]
First of all I'm a noob.

I tried to use neuron.nvim first. It did not work. It would display nothing in search of telescope.nvim. So I figured I try this plugin.
At first this didn't work. I figured mappings are not configured by default so I used configured the plugin to its defaults.

I went inside my zettels directory, opened up neovim and tried `gzz`. Result is `Error!`. Not very helpful.
And so I am stuck. No idea why it doesn't work. Please tell me what info I can provide.

Using the latest neuron release. Nvim 0.5.0. Installed with plug, configured to defaults.
Working: Everything except search_zettel `gzz`. 

Please help me before I lose my sanity. It's been hours and I can't configure any neovim neuron plugin to its basic functionality...

**Comment by ardasevinc** [comment]
SOLVED IT!

 ## The Problem
 It was the *neuron binary*. I installed it from AUR and that got the binary from [neuron releases](https://github.com/srid/neuron/releases).
 The problem is that it is **version 1.0.1.0**
 Installing it with nix pkg manager solved the issue.

**Comment by pyrho** [comment]
Glad to hear to solved it !

I [just added](https://github.com/pyrho/nerveux.nvim#troubleshooting) a health check and some instructions in the README.

**Comment by ardasevinc** [comment]
> Glad to hear to solved it !
> 
> I [just added](https://github.com/pyrho/nerveux.nvim#troubleshooting) a health check and some instructions in the README.

Thank you! By the way I just updated the plugin with vim-plug and got this after running `:checkhealth nerveux`

![image](https://user-images.githubusercontent.com/42278637/125159120-1175e500-e17e-11eb-8f3c-05c880d9727d.png)

**Comment by pyrho** [comment]
Oops nice catch I forgot to remove a call to a debug function. Fixed thank you for reporting !
