### ISSUE TITLE
Plugin doesn't work when there are spaces in the path

### ISSUE THREAD

**Issue by ardasevinc** [pyrho/nerveux.nvim#4]
## Steps to reproduce

1. have spaces in your cwd name. (~/docs/spaces in this folder/zettel.md)
2. create a neuron.dhall and a markdown file and edit it
3. try to use any shortcuts like gzz, gzn

**Comment by pyrho** [comment]
Hi,

Sorry for the late response, I believe the issue is now fixed by https://github.com/pyrho/nerveux.nvim/commit/ebca6a90d84944e1eee44221559ce0436771d51e .
